# Generated by Django 3.2.3 on 2021-06-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210603_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='DEPT_name',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
