# Generated by Django 3.2.3 on 2021-06-03 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_department_dept_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='School',
        ),
    ]
