# Generated by Django 3.2.3 on 2021-06-04 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_name_department_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='DEPT_name',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
