# Generated by Django 3.2.3 on 2021-06-04 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210604_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='DEPT_name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='Certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.certificate'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.grade'),
        ),
    ]
